In [4]:
Name = "Divyanshu"
Age=21
print("Name:", Name, ",", "Age:", Age)

Name: Divyanshu , Age: 21


In [2]:
X="Datascience is used to extract meaningful insights."
Y = X.split()
print(Y)

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']


In [3]:
X = int(input("Input 1st number"))
Y = int(input("Input 2nd number"))

def product(X,Y):
    multiply=X*Y;
    return multiply;
print("The product is",product(X,Y))

Input 1st number2
Input 2nd number4
The product is 8


In [5]:
St_capitals = { "Uttar Pradesh":"Lucknow",
             "Tamil Nadu ": "Chennai",
             "Rajasthan": "Jaipur",
             "Maharashtra": "Mumbai",
             "Madhya Pradesh": "Bhopal" }
print("Dictionary : ", St_capitals)
print(St_capitals.keys())
print(St_capitals.values())

Dictionary :  {'Uttar Pradesh': 'Lucknow', 'Tamil Nadu ': 'Chennai', 'Rajasthan': 'Jaipur', 'Maharashtra': 'Mumbai', 'Madhya Pradesh': 'Bhopal'}
dict_keys(['Uttar Pradesh', 'Tamil Nadu ', 'Rajasthan', 'Maharashtra', 'Madhya Pradesh'])
dict_values(['Lucknow', 'Chennai', 'Jaipur', 'Mumbai', 'Bhopal'])


In [7]:
Numbers = list(range(1, 1000))
print(Numbers)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 22

In [8]:
import numpy as np

dimension = 4
identity_matrix = np.identity(dimension, dtype="int")
print(identity_matrix)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [10]:
import numpy as np
x =  np.arange(1, 10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
array = [
   [1, 2, 3],
   [4, 5, 6]
]
result = list(map(sum, array))
print(result)

[6, 15]


In [12]:
import numpy as np
 
arr1 = np.array([3, 2, 1])
arr2 = np.array([1, 2, 3])
   
print ("1st array : ", arr1)  
print ("2nd array : ", arr2)  
   
out_arr = np.add(arr1, arr2)  
print ("added array : ", out_arr)  

1st array :  [3 2 1]
2nd array :  [1 2 3]
added array :  [4 4 4]


In [15]:
from datetime import date, timedelta

start_dt = date(2023, 2, 1)
end_dt = date(2023, 3, 1)


delta = timedelta(days=1)


dates = []

while start_dt <= end_dt:
    
    dates.append(start_dt.isoformat())
    
    start_dt += delta

print('Dates between', start_dt, 'and', end_dt)
print(dates)

Dates between 2023-03-02 and 2023-03-01
['2023-02-01', '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05', '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09', '2023-02-10', '2023-02-11', '2023-02-12', '2023-02-13', '2023-02-14', '2023-02-15', '2023-02-16', '2023-02-17', '2023-02-18', '2023-02-19', '2023-02-20', '2023-02-21', '2023-02-22', '2023-02-23', '2023-02-24', '2023-02-25', '2023-02-26', '2023-02-27', '2023-02-28', '2023-03-01']


In [18]:
import pandas as pd

details = {
    'Brand' : ['Maruti', 'Renault', 'Hyndai'],
    'Sales' : [250, 200, 240]
}

df = pd.DataFrame(details)
  
df

Brand  Sales
0   Maruti    250
1  Renault    200
2   Hyndai    240